name: SmallRye Build

on:
  push:
    branches:
      - main
      - "1.x"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 16, 17-ea]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven

      - uses: actions/setup-java@v2
        name: set up jdk ${{matrix.java}}
        with:
          distribution: adopt
          java-version: ${{matrix.java}}

      - name: validate format
        run: mvn -s .build/maven-ci-settings.xml -f pom.xml -B -pl '!vertx-mutiny-clients-bom' formatter:validate
      - name: build with maven
        run: mvn -s .build/maven-ci-settings.xml -f pom.xml -B verify

  quality:
    needs: [build]
    if: github.event_name == 'push' && startsWith('smallrye', github.repository)
    runs-on: ubuntu-latest
    name: quality

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven
      - name: sonar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -s .build/maven-ci-settings.xml -B -f pom.xml -Pcoverage verify javadoc:javadoc sonar:sonar -Dsonar.projectKey=smallrye_smallrye-mutiny-vertx-bindings -Dsonar.login=$SONAR_TOKEN
